server:
  port: 7070

spring:
  application:
    name: demo-consumer

eureka:
  client:
    # 消费方，必须要向eureka注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka/

